name: catproject
description: "App to learn about fluter, bloc pattern and testing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.2.0
  mocktail: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
